### ISSUE TITLE
[Feat] CI/CD 구축

### ISSUE THREAD

**Issue by morenow98** [BookitList/BookitList_backend#3]
## Description
프로젝트 자동 배포를 위한 CI/CD를 구축한다.
github actions를 통해 AWS S3에 파일을 업로드하고 AWS CodeDeploy를 통해 AWS EC2에 배포한다.
![image](https://github.com/BookitList/BookitList_backend/assets/112200350/3efac7d3-13f3-4a61-b985-7f7cf4e6fb6f)

## Todo
* [x] AWS EC2 설정
* [x] AWS S3 설정
* [x] AWS CodeDeploy 설정
* [x] github actions 및 프로젝트 코드 설정

## ETC
pull request를 날릴 때 배포할 것인지 push 할 때 배포할 것인지
