### ISSUE TITLE
[Feat] 한줄요약 좋아요 기능 추가

### ISSUE THREAD

**Issue by morenow98** [BookitList/BookitList_backend#95]
## Description
한줄요약 조회 시 좋아요 기능 추가, 추가 정보 제공

## Todo
* [x] 한줄요약 조회 시 좋아요 기능 추가
* [x] 한줄요약 검색 시 좋아요 기능 추가
* [x] 한줄요약 조회, 검색 시 좋아요 유무 파악할 수 있도록 기능 추가
* [x] 한줄요약 상세 조회 시 생성일, 수정일, 작성자 정보를 추가로 보내주도록 변경
* [x] 한줄요약 좋아요 서비스 테스트 코드 구현
* [x] 한줄요약 좋아요 컨트롤러 테스트 코드 구현
* [x] 한줄요약 컨트롤러 테스트 코드 수정

## ETC
기타사항
